//----------------------------------------------------------------------------------------------------------------------
// GraphicsTypeRegistration.cpp
//
// Copyright (C) 2010 WhiteMoon Dreams, Inc.
// All Rights Reserved
//----------------------------------------------------------------------------------------------------------------------

// !!! AUTOGENERATED FILE - DO NOT EDIT !!!

#include "GraphicsPch.h"
#include "Platform/Assert.h"
#include "Engine/Package.h"

#include "Graphics/Material.h"
#include "Graphics/Shader.h"
#include "Graphics/Animation.h"
#include "Graphics/Texture2d.h"
#include "Graphics/GraphicsConfig.h"
#include "Graphics/GraphicsScene.h"
#include "Graphics/Texture.h"

static Lunar::StrongPtr< Lunar::Package > spGraphicsTypePackage;

LUNAR_GRAPHICS_API Lunar::Package* GetGraphicsTypePackage()
{
    Lunar::Package* pPackage = spGraphicsTypePackage;
    if( !pPackage )
    {
        Lunar::Object* pTypesPackageObject = Lunar::Object::FindChildOf( NULL, Lunar::Name( TXT( "Types" ) ) );
        HELIUM_ASSERT( pTypesPackageObject );
        HELIUM_ASSERT( pTypesPackageObject->IsPackage() );

        pPackage = Lunar::Object::Create< Lunar::Package >( Lunar::Name( TXT( "Graphics" ) ), pTypesPackageObject );
        HELIUM_ASSERT( pPackage );
        spGraphicsTypePackage = pPackage;
    }

    return pPackage;
}

LUNAR_GRAPHICS_API void ReleaseGraphicsTypePackage()
{
    spGraphicsTypePackage = NULL;
}

LUNAR_GRAPHICS_API void RegisterGraphicsTypes()
{
    HELIUM_VERIFY( GetGraphicsTypePackage() );

    HELIUM_VERIFY( Lunar::Animation::InitStaticType() );
    HELIUM_VERIFY( Lunar::GraphicsConfig::InitStaticType() );
    HELIUM_VERIFY( Lunar::GraphicsScene::InitStaticType() );
    HELIUM_VERIFY( Lunar::Material::InitStaticType() );
    HELIUM_VERIFY( Lunar::Shader::InitStaticType() );
    HELIUM_VERIFY( Lunar::ShaderVariant::InitStaticType() );
    HELIUM_VERIFY( Lunar::Texture::InitStaticType() );
    HELIUM_VERIFY( Lunar::Texture2d::InitStaticType() );
}

LUNAR_GRAPHICS_API void UnregisterGraphicsTypes()
{
    Lunar::Animation::ReleaseStaticType();
    Lunar::GraphicsConfig::ReleaseStaticType();
    Lunar::GraphicsScene::ReleaseStaticType();
    Lunar::Material::ReleaseStaticType();
    Lunar::Shader::ReleaseStaticType();
    Lunar::ShaderVariant::ReleaseStaticType();
    Lunar::Texture::ReleaseStaticType();
    Lunar::Texture2d::ReleaseStaticType();

    ReleaseGraphicsTypePackage();
}
