//----------------------------------------------------------------------------------------------------------------------
// PcSupportTypeRegistration.cpp
//
// Copyright (C) 2010 WhiteMoon Dreams, Inc.
// All Rights Reserved
//----------------------------------------------------------------------------------------------------------------------

// !!! AUTOGENERATED FILE - DO NOT EDIT !!!

#include "PcSupportPch.h"
#include "Platform/Assert.h"
#include "Engine/Package.h"

#include "PcSupport/ResourceHandler.h"

static Lunar::StrongPtr< Lunar::Package > spPcSupportTypePackage;

LUNAR_PC_SUPPORT_API Lunar::Package* GetPcSupportTypePackage()
{
    Lunar::Package* pPackage = spPcSupportTypePackage;
    if( !pPackage )
    {
        Lunar::Object* pTypesPackageObject = Lunar::Object::FindChildOf( NULL, Lunar::Name( TXT( "Types" ) ) );
        HELIUM_ASSERT( pTypesPackageObject );
        HELIUM_ASSERT( pTypesPackageObject->IsPackage() );

        pPackage = Lunar::Object::Create< Lunar::Package >( Lunar::Name( TXT( "PcSupport" ) ), pTypesPackageObject );
        HELIUM_ASSERT( pPackage );
        spPcSupportTypePackage = pPackage;
    }

    return pPackage;
}

LUNAR_PC_SUPPORT_API void ReleasePcSupportTypePackage()
{
    spPcSupportTypePackage = NULL;
}

LUNAR_PC_SUPPORT_API void RegisterPcSupportTypes()
{
    HELIUM_VERIFY( GetPcSupportTypePackage() );

    HELIUM_VERIFY( Lunar::ResourceHandler::InitStaticType() );
}

LUNAR_PC_SUPPORT_API void UnregisterPcSupportTypes()
{
    Lunar::ResourceHandler::ReleaseStaticType();

    ReleasePcSupportTypePackage();
}
