#ifndef __LitesqlDatabasePanel__
#define __LitesqlDatabasePanel__

/**
@file
Subclass of DatabasePanel, which is generated by wxFormBuilder.
*/

#include "ui.h"

#include "objectmodel.hpp"

namespace ui {

  /** Implementing DatabasePanel */
  class LitesqlDatabasePanel : public DatabasePanel
  {
  public:
    /** Constructor */
    LitesqlDatabasePanel( wxWindow* parent, xml::DatabasePtr& db );

  private:
    xml::DatabasePtr m_database;
  };

}
#endif // __LitesqlDatabasePanel__