#ifndef __LitesqlGeneratePanel__
#define __LitesqlGeneratePanel__

/**
@file
Subclass of GeneratePanel, which is generated by wxFormBuilder.
*/

#include "ui.h"

namespace litesql {
  class ObjectModel;
}


/** Implementing GeneratePanel */
class LitesqlGeneratePanel : public ui::GeneratePanel
{
public:
	/** Constructor */
	LitesqlGeneratePanel( wxWindow* parent,litesql::ObjectModel* pModel);

protected:
  virtual void OnRunClick( wxCommandEvent& event );
private:
  litesql::ObjectModel* m_pModel;
};

#endif // __LitesqlGeneratePanel__