#ifndef __LitesqlRelationPanel__
#define __LitesqlRelationPanel__

/**
@file
Subclass of RelationPanel, which is generated by wxFormBuilder.
*/
#include <vector>
#include <wx/valgen.h>

#include "ui.h"
#include "xmlobjects.hpp"

/**Validator for a wxChoice <-> xml::Field::type */
class RelateTypeValidator : public wxGenericValidator {

  DECLARE_DYNAMIC_CLASS(RelateTypeValidator)

public:
  
  RelateTypeValidator (xml::Relate::counted_ptr val = xml::Relate::counted_ptr(NULL));
  RelateTypeValidator (const RelateTypeValidator& val);

  virtual wxObject *Clone() const;
    
  // Called to transfer data to the window
  virtual bool TransferToWindow();

    // Called to transfer data from the window
  virtual bool TransferFromWindow();

private:
  xml::Relate::counted_ptr m_pRelate;
  wxString value; 
};

/** Implementing RelationPanel */
class LitesqlRelationPanel : public ui::RelationPanel
{
public:
  /** Constructor */
  LitesqlRelationPanel( wxWindow* parent , xml::Relation::counted_ptr& pRelation);
  void setBaseClasses(const xml::ObjectSequence& baseClasses);

private:
  xml::Relation::counted_ptr m_pRelation;
};

#endif // __LitesqlRelationPanel__