#ifndef __LitesqlRelationPanel__
#define __LitesqlRelationPanel__

/**
@file
Subclass of RelationPanel, which is generated by wxFormBuilder.
*/

#include "ui.h"

namespace xml 
{
  class Relation;
}

/** Implementing RelationPanel */
class LitesqlRelationPanel : public ui::RelationPanel
{
public:
  /** Constructor */
  LitesqlRelationPanel( wxWindow* parent , xml::Relation* pRelation);

private:
  xml::Relation* m_pRelation;
};

#endif // __LitesqlRelationPanel__