#pragma once

#include "Foundation/Profile.h"

#define HELIUM_PIPELINE_PROFILE 0

#if HELIUM_PROFILE_INSTRUMENT_ALL || HELIUM_PIPELINE_PROFILE
# define HELIUM_PIPELINE_SCOPE_TIMER( ... ) HELIUM_PROFILE_SCOPE_TIMER( __VA_ARGS__ )
#else
# define HELIUM_PIPELINE_SCOPE_TIMER( ... )
#endif

#define HELIUM_PIPELINE_PROFILE_RENDER 0

#if HELIUM_PROFILE_INSTRUMENT_ALL || HELIUM_PIPELINE_PROFILE_RENDER
# define HELIUM_PIPELINE_RENDER_SCOPE_TIMER( ... ) HELIUM_PROFILE_SCOPE_TIMER( __VA_ARGS__ )
#else
# define HELIUM_PIPELINE_RENDER_SCOPE_TIMER( ... )
#endif