import os, sys, platform

Import("env")

# Build the DLL
libsources = [ "nedmalloc.c" ]
if sys.platform=='win32': libsources+=["winpatcher.c"]
libobjects = env.SharedObject(source = libsources, CPPDEFINES=env['CPPDEFINES']+["NEDMALLOC_DLL_EXPORTS"])
if sys.platform=='win32': libobjects+=env.RES("nedmalloc.res", "nedmalloc_dll.rc")
nedmalloclib = env.SharedLibrary("nedmalloc", source = libobjects)
if sys.platform=='win32': env.AddPostAction(nedmalloclib, 'mt.exe -nologo -manifest ${TARGET}.manifest -outputresource:$TARGET;2')
nedmallocliblib = nedmalloclib
if sys.platform=='win32':
    #env.AddPreAction(env.AddPreAction(nedmalloclib, "pgomgr /clear ${VARIANT}/nedmalloc.pgd"), "pgomgr /merge ${VARIANT}/nedmalloc.pgd")
    nedmallocliblib=nedmalloclib[1]

# Test program
sources = [ "test.c" ]
objects = env.Object(source = sources) # + [nedmallocliblib]
testlibs=[nedmallocliblib]
if sys.platform=='win32': testlibs+=["user32"]
testprogram = env.Program("test", source = objects, LINKFLAGS=[], LIBS = testlibs)

Default(testprogram)
Return("nedmalloclib")
