//----------------------------------------------------------------------------------------------------------------------
// ExampleGameTypeRegistration.cpp
//
// Copyright (C) 2012 WhiteMoon Dreams, Inc.
// All Rights Reserved
//----------------------------------------------------------------------------------------------------------------------

// !!! AUTOGENERATED FILE - DO NOT EDIT !!!

#include "ExampleGamePch.h"
#include "Platform/Assert.h"
#include "Engine/Package.h"

#include "ExampleGame/ExampleObject.h"

static Helium::StrongPtr< Helium::Package > spExampleGameTypePackage;

EXAMPLE_EXAMPLE_GAME_API Helium::Package* GetExampleGameTypePackage()
{
    Helium::Package* pPackage = spExampleGameTypePackage;
    if( !pPackage )
    {
        Helium::GameObject* pTypesPackageObject = Helium::GameObject::FindChildOf( NULL, Helium::Name( TXT( "Types" ) ) );
        HELIUM_ASSERT( pTypesPackageObject );
        HELIUM_ASSERT( pTypesPackageObject->IsPackage() );

        HELIUM_VERIFY( Helium::GameObject::Create< Helium::Package >(
            spExampleGameTypePackage,
            Helium::Name( TXT( "ExampleGame" ) ),
            pTypesPackageObject ) );
        pPackage = spExampleGameTypePackage;
        HELIUM_ASSERT( pPackage );
    }

    return pPackage;
}

EXAMPLE_EXAMPLE_GAME_API void ReleaseExampleGameTypePackage()
{
    spExampleGameTypePackage = NULL;
}

EXAMPLE_EXAMPLE_GAME_API void RegisterExampleGameTypes()
{
    HELIUM_VERIFY( GetExampleGameTypePackage() );

    HELIUM_VERIFY( Example::ExampleObject::InitStaticType() );
}

EXAMPLE_EXAMPLE_GAME_API void UnregisterExampleGameTypes()
{
    Example::ExampleObject::ReleaseStaticType();

    ReleaseExampleGameTypePackage();
}
