//----------------------------------------------------------------------------------------------------------------------
// ExampleGameTypeRegistration.cpp
//
// Copyright (C) 2011 WhiteMoon Dreams, Inc.
// All Rights Reserved
//----------------------------------------------------------------------------------------------------------------------

// !!! AUTOGENERATED FILE - DO NOT EDIT !!!

#include "ExampleGamePch.h"
#include "Platform/Assert.h"
#include "Engine/Package.h"

#include "ExampleGame/ExampleObject.h"

static Lunar::StrongPtr< Lunar::Package > spExampleGameTypePackage;

EXAMPLE_EXAMPLE_GAME_API Lunar::Package* GetExampleGameTypePackage()
{
    Lunar::Package* pPackage = spExampleGameTypePackage;
    if( !pPackage )
    {
        Lunar::GameObject* pTypesPackageObject = Lunar::GameObject::FindChildOf( NULL, Lunar::Name( TXT( "Types" ) ) );
        HELIUM_ASSERT( pTypesPackageObject );
        HELIUM_ASSERT( pTypesPackageObject->IsPackage() );

        HELIUM_VERIFY( Lunar::GameObject::Create< Lunar::Package >(
            spExampleGameTypePackage,
            Lunar::Name( TXT( "ExampleGame" ) ),
            pTypesPackageObject ) );
        pPackage = spExampleGameTypePackage;
        HELIUM_ASSERT( pPackage );
    }

    return pPackage;
}

EXAMPLE_EXAMPLE_GAME_API void ReleaseExampleGameTypePackage()
{
    spExampleGameTypePackage = NULL;
}

EXAMPLE_EXAMPLE_GAME_API void RegisterExampleGameTypes()
{
    HELIUM_VERIFY( GetExampleGameTypePackage() );

    HELIUM_VERIFY( Example::ExampleObject::InitStaticType() );
}

EXAMPLE_EXAMPLE_GAME_API void UnregisterExampleGameTypes()
{
    Example::ExampleObject::ReleaseStaticType();

    ReleaseExampleGameTypePackage();
}
