#ifndef __LitesqlObjectPanel__
#define __LitesqlObjectPanel__

/**
@file
Subclass of ObjectPanel, which is generated by wxFormBuilder.
*/

#include <vector>
#include <wx/valgen.h>

#include "ui.h"

namespace xml 
{
  class Object;
}
/**Validator for a wxChoice <-> xml::Field::type */
class ObjectTypeValidator : public wxGenericValidator {

  DECLARE_DYNAMIC_CLASS(ObjectTypeValidator)

public:
  
  ObjectTypeValidator (xml::Object *val = 0);
  ObjectTypeValidator (const ObjectTypeValidator& val);

  virtual wxObject *Clone() const;
    
  // Called to transfer data to the window
  virtual bool TransferToWindow();

    // Called to transfer data from the window
  virtual bool TransferFromWindow();

private:
  xml::Object *m_pObject;
  wxString value; 
};

/** Implementing ObjectPanel */
class LitesqlObjectPanel : public ui::ObjectPanel
{
public:
	/** Constructor */
  LitesqlObjectPanel( wxWindow* parent, std::vector<xml::Object*> baseClasses,xml::Object* pObject );
  xml::Object* GetObject();

private:
  LitesqlObjectPanel(): ui::ObjectPanel(NULL) {};

  xml::Object* m_pObject;
  DECLARE_DYNAMIC_CLASS(LitesqlObjectPanel);
};

#endif // __LitesqlObjectPanel__
