#ifndef __LitesqlMethodPanel__
#define __LitesqlMethodPanel__

/**
@file
Subclass of FieldPanel, which is generated by wxFormBuilder.
*/

#include "objectmodel.hpp"

#include "ui.h"
#include "ddx.h"

/** Implementing FieldPanel */
class LitesqlMethodPanel : public ui::MethodPanel
{
public:
	/** Constructor */
  LitesqlMethodPanel( wxWindow* parent , xml::Method* pMethod);

private:
  xml::Method* m_pMethod;
};

#endif // __LitesqlMethodPanel__
