//----------------------------------------------------------------------------------------------------------------------
// FrameworkInterface.cpp
//
// Copyright (C) 2010 WhiteMoon Dreams, Inc.
// All Rights Reserved
//----------------------------------------------------------------------------------------------------------------------

// !!! AUTOGENERATED FILE - DO NOT EDIT !!!

#include "FrameworkPch.h"
#include "Framework/FrameworkInterface.h"

#include "Platform/Assert.h"

namespace Lunar
{

}  // namespace Lunar

