//----------------------------------------------------------------------------------------------------------------------
// FrameworkTypeRegistration.cpp
//
// Copyright (C) 2010 WhiteMoon Dreams, Inc.
// All Rights Reserved
//----------------------------------------------------------------------------------------------------------------------

// !!! AUTOGENERATED FILE - DO NOT EDIT !!!

#include "FrameworkPch.h"
#include "Platform/Assert.h"
#include "Engine/Package.h"

#include "Framework/Layer.h"
#include "Framework/MeshEntity.h"
#include "Framework/Mesh.h"
#include "Framework/Entity.h"
#include "Framework/Camera.h"
#include "Framework/SkeletalMeshEntity.h"
#include "Framework/StaticMeshEntity.h"
#include "Framework/World.h"

static Lunar::StrongPtr< Lunar::Package > spFrameworkTypePackage;

LUNAR_FRAMEWORK_API Lunar::Package* GetFrameworkTypePackage()
{
    Lunar::Package* pPackage = spFrameworkTypePackage;
    if( !pPackage )
    {
        Lunar::Object* pTypesPackageObject = Lunar::Object::FindChildOf( NULL, Lunar::Name( TXT( "Types" ) ) );
        HELIUM_ASSERT( pTypesPackageObject );
        HELIUM_ASSERT( pTypesPackageObject->IsPackage() );

        pPackage = Lunar::Object::Create< Lunar::Package >( Lunar::Name( TXT( "Framework" ) ), pTypesPackageObject );
        HELIUM_ASSERT( pPackage );
        spFrameworkTypePackage = pPackage;
    }

    return pPackage;
}

LUNAR_FRAMEWORK_API void ReleaseFrameworkTypePackage()
{
    spFrameworkTypePackage = NULL;
}

LUNAR_FRAMEWORK_API void RegisterFrameworkTypes()
{
    HELIUM_VERIFY( GetFrameworkTypePackage() );

    HELIUM_VERIFY( Lunar::Camera::InitStaticType() );
    HELIUM_VERIFY( Lunar::Entity::InitStaticType() );
    HELIUM_VERIFY( Lunar::Layer::InitStaticType() );
    HELIUM_VERIFY( Lunar::Mesh::InitStaticType() );
    HELIUM_VERIFY( Lunar::MeshEntity::InitStaticType() );
    HELIUM_VERIFY( Lunar::SkeletalMeshEntity::InitStaticType() );
    HELIUM_VERIFY( Lunar::StaticMeshEntity::InitStaticType() );
    HELIUM_VERIFY( Lunar::World::InitStaticType() );
}

LUNAR_FRAMEWORK_API void UnregisterFrameworkTypes()
{
    Lunar::Camera::ReleaseStaticType();
    Lunar::Entity::ReleaseStaticType();
    Lunar::Layer::ReleaseStaticType();
    Lunar::Mesh::ReleaseStaticType();
    Lunar::MeshEntity::ReleaseStaticType();
    Lunar::SkeletalMeshEntity::ReleaseStaticType();
    Lunar::StaticMeshEntity::ReleaseStaticType();
    Lunar::World::ReleaseStaticType();

    ReleaseFrameworkTypePackage();
}
