#pragma once

#include "Foundation/Profile.h"

#define HELIUM_EDITOR_PROFILE 0

#if HELIUM_PROFILE_INSTRUMENT_ALL || HELIUM_EDITOR_PROFILE
# define EDITOR_SCOPE_TIMER(__Str) HELIUM_PROFILE_SCOPE_TIMER(__Str)
#else
# define EDITOR_SCOPE_TIMER(__Str)
#endif

#define HELIUM_EDITOR_PROFILE_RENDER 0

#if HELIUM_PROFILE_INSTRUMENT_ALL || HELIUM_EDITOR_PROFILE_RENDER
# define HELIUM_EDITOR_RENDER_SCOPE_TIMER(__Str) HELIUM_PROFILE_SCOPE_TIMER(__Str)
#else
# define HELIUM_EDITOR_RENDER_SCOPE_TIMER(__Str)
#endif