#pragma once

#define NOCTURNAL_VERSION_PROJECT     1
#define NOCTURNAL_VERSION_COMPATIBLE  1
#define NOCTURNAL_VERSION_FEATURE     0
#define NOCTURNAL_VERSION_PATCH       6

#define NOCTURNAL_VERSION_STRINGIFY(project, compatible, feature, patch) #project"."#compatible"."#feature"."#patch
#define NOCTURNAL_VERSION_TOSTRING(project, compatible, feature, patch) NOCTURNAL_VERSION_STRINGIFY(project,compatible,feature,patch)
#define NOCTURNAL_VERSION_STRING NOCTURNAL_VERSION_TOSTRING( NOCTURNAL_VERSION_PROJECT, NOCTURNAL_VERSION_COMPATIBLE, NOCTURNAL_VERSION_FEATURE, NOCTURNAL_VERSION_PATCH)
