//----------------------------------------------------------------------------------------------------------------------
// TestJobsInterface.cpp
//
// Copyright (C) 2010 WhiteMoon Dreams, Inc.
// All Rights Reserved
//----------------------------------------------------------------------------------------------------------------------

// !!! AUTOGENERATED FILE - DO NOT EDIT !!!

#include "TestJobsPch.h"
#include "TestJobs/TestJobsInterface.h"

#include "Platform/Assert.h"

namespace Lunar
{

}  // namespace Lunar

