LiteSQL: litesql::Backend Class Reference
litesql::Backend Class Reference
An abstract base class for interfacing with relational databases.
#include <backend.hpp>
Public Member Functions
virtual ~Backend ()
empty
virtual bool supportsSequences () const
return true if backend supports CREATE SEQUENCE - SQL-statements
virtual string getRowIDType () const
backend may want to set an AUTO_INCREMENT-attribute for table's primary key field.
virtual string getInsertID () const
if backend supports this, new primary key of the last insert is returned
virtual void begin () const
begin SQL transaction, may or may not have an effect
virtual void commit () const
commit SQL transaction
virtual void rollback () const
rollback SQL transaction
virtual Result * execute (string query) const =0
executes SQL-query
virtual Cursor * cursor (string query) const =0
executes SQL-query
virtual string groupInsert (Record tables, Records fields, Records values, string sequence) const
executes multiple INSERT-statements and assigns same 'row id' for first field of every record
Classes
class Cursor
An abstract base class for cursors that iterate result sets returned by relational database.
class Result
Detailed Description
An abstract base class for interfacing with relational databases.
Member Function Documentation
virtual string litesql::Backend::getRowIDType () const [inline, virtual]
backend may want to set an AUTO_INCREMENT-attribute for table's primary key field.
this method is to deliver the details to database schema
virtual Result* litesql::Backend::execute (string query) const [pure virtual]
executes SQL-query
Parameters:
query SQL-query to execute
Returns:
Result-object which holds result set of query
Referenced by groupInsert(), and litesql::Database::query().
virtual Cursor* litesql::Backend::cursor (string query) const [pure virtual]
executes SQL-query
Parameters:
query SQL-query to execute
Returns:
Cursor-object which can be used to iterate result set row by row without loading everything to memory
string litesql::Backend::groupInsert (Record tables, Records fields, Records values, string sequence) const [virtual]
executes multiple INSERT-statements and assigns same 'row id' for first field of every record
Parameters:
tables destination tables for insert operation
fields record of field names per table
values record of values per table
sequence sequence where row id-numbers are pulled
Returns:
new row id
References execute(), getInsertID(), litesql::Split::join(), and supportsSequences().
Referenced by litesql::Database::groupInsert().
The documentation for this class was generated from the following files:
backend.hpp
backend.cpp