LiteSQL: litesql::DataSource< T > Class Template Reference
litesql::DataSource< T > Class Template Reference
template class which holds SelectQuery for selecting objects of type T
#include <datasource.hpp>
Public Member Functions
DataSource (const Database &db_, const Expr &e=Expr())
DataSource (const Database &db_, const SelectQuery &sel_)
const Database & getDatabase () const
returns database reference
SelectQuery idQuery () const
returns SelectQuery which selects ID-numbers of objects
size_t count () const
returns number of objects in result set
SelectQuery objectQuery () const
returns SelectQuery which selects objects
Cursor< T > cursor () const
returns cursor for query
T one () const
returns first object in result set.
vector< T > all () const
returns all objects in result set.
DataSource & orderBy (FieldType f, bool asc=true)
modifies SelectQuery to order result set
DataSource & orderByRelation (FieldType id, FieldType f, bool asc=true)
modifies SelectQuery to order result set by external table
Detailed Description
template<class T>
class litesql::DataSource< T >
template class which holds SelectQuery for selecting objects of type T
Constructor & Destructor Documentation
template<class T> litesql::DataSource< T >::DataSource (const Database & db_, const Expr & e = Expr()) [inline]
Parameters:
db_ database reference
e selection filter
template<class T> litesql::DataSource< T >::DataSource (const Database & db_, const SelectQuery & sel_) [inline]
Parameters:
db_ database reference
sel_ selection query
Member Function Documentation
template<class T> T litesql::DataSource< T >::one () const [inline]
returns first object in result set.
throw exception if none found
Returns:
object of type T
References litesql::DataSource< T >::cursor().
template<class T> vector<T> litesql::DataSource< T >::all () const [inline]
returns all objects in result set.
References litesql::DataSource< T >::cursor().
template<class T> DataSource& litesql::DataSource< T >::orderBy (FieldType f, bool asc = true) [inline]
modifies SelectQuery to order result set
Parameters:
f field to order by
asc ascending order
Returns:
*this, methods can be chained
References litesql::SelectQuery::orderBy().
template<class T> DataSource& litesql::DataSource< T >::orderByRelation (FieldType id, FieldType f, bool asc = true) [inline]
modifies SelectQuery to order result set by external table
Parameters:
id foreign key field used to join table with query
f field to order by
asc ascending order
Returns:
*this, methods can be chained
References litesql::SelectQuery::orderBy(), litesql::SelectQuery::source(), and litesql::SelectQuery::where().
The documentation for this class was generated from the following file:
datasource.hpp