//----------------------------------------------------------------------------------------------------------------------
// GraphicsJobsInterface.cpp
//
// Copyright (C) 2010 WhiteMoon Dreams, Inc.
// All Rights Reserved
//----------------------------------------------------------------------------------------------------------------------

// !!! AUTOGENERATED FILE - DO NOT EDIT !!!

#include "GraphicsJobsPch.h"
#include "GraphicsJobs/GraphicsJobsInterface.h"

#include "Platform/Assert.h"

namespace Lunar
{

}  // namespace Lunar

