//----------------------------------------------------------------------------------------------------------------------
// GraphicsJobsInterface.h
//
// Copyright (C) 2010 WhiteMoon Dreams, Inc.
// All Rights Reserved
//----------------------------------------------------------------------------------------------------------------------

// !!! AUTOGENERATED FILE - DO NOT EDIT !!!

#pragma once
#ifndef LUNAR_GRAPHICS_JOBS_GRAPHICS_JOBS_INTERFACE_H
#define LUNAR_GRAPHICS_JOBS_GRAPHICS_JOBS_INTERFACE_H

#include "GraphicsJobs/GraphicsJobs.h"
#include "Platform/Assert.h"
#include "GraphicsTypes/GraphicsSceneObject.h"

namespace Lunar
{
    class JobContext;
}

namespace Lunar
{

/// Spawn jobs to update all instance constant buffers for graphics scene objects and sub-meshes.
class LUNAR_GRAPHICS_JOBS_API UpdateGraphicsSceneConstantBuffersJobSpawner : Lunar::NonCopyable
{
public:
    class Parameters
    {
    public:
        /// [in] Number of elements in the scene object array.
        uint32_t sceneObjectCount;
        /// [in] Number of elements in the sub-mesh array.
        uint32_t subMeshCount;
        /// [in] Array of scene objects to update.
        const GraphicsSceneObject* pSceneObjects;
        /// [in] Array of buffers in which to store the constant buffer data for each scene object.
        float32_t* const* ppSceneObjectConstantBufferData;
        /// [in] Array of sub-meshes to update.
        const GraphicsSceneObject::SubMeshData* pSubMeshes;
        /// [in] Array of buffers in which to store the constant buffer data for each sub-mesh.
        float32_t* const* ppSubMeshConstantBufferData;

        /// @name Construction/Destruction
        //@{
        inline Parameters();
        //@}
    };

    /// @name Construction/Destruction
    //@{
    inline UpdateGraphicsSceneConstantBuffersJobSpawner();
    inline ~UpdateGraphicsSceneConstantBuffersJobSpawner();
    //@}

    /// @name Parameters
    //@{
    inline Parameters& GetParameters();
    inline const Parameters& GetParameters() const;
    inline void SetParameters( const Parameters& rParameters );
    //@}

    /// @name Job Execution
    //@{
    void Run( JobContext* pContext );
    inline static void RunCallback( void* pJob, JobContext* pContext );
    //@}

private:
    Parameters m_parameters;
};

/// Spawn jobs to update the constant buffer data for all graphics scene objects.
class LUNAR_GRAPHICS_JOBS_API UpdateGraphicsSceneObjectBuffersJobSpawner : Lunar::NonCopyable
{
public:
    class Parameters
    {
    public:
        /// [in] Number of elements in the scene object array.
        uint32_t sceneObjectCount;
        /// [in] Array of scene objects to update.
        const GraphicsSceneObject* pSceneObjects;
        /// [out] Array of buffers in which to store the constant buffer data for each scene object.
        float32_t* const* ppConstantBufferData;

        /// @name Construction/Destruction
        //@{
        inline Parameters();
        //@}
    };

    /// @name Construction/Destruction
    //@{
    inline UpdateGraphicsSceneObjectBuffersJobSpawner();
    inline ~UpdateGraphicsSceneObjectBuffersJobSpawner();
    //@}

    /// @name Parameters
    //@{
    inline Parameters& GetParameters();
    inline const Parameters& GetParameters() const;
    inline void SetParameters( const Parameters& rParameters );
    //@}

    /// @name Job Execution
    //@{
    void Run( JobContext* pContext );
    inline static void RunCallback( void* pJob, JobContext* pContext );
    //@}

private:
    Parameters m_parameters;
};

/// Spawn jobs to update the constant buffer data for all graphics scene object sub-meshes.
class LUNAR_GRAPHICS_JOBS_API UpdateGraphicsSceneSubMeshBuffersJobSpawner : Lunar::NonCopyable
{
public:
    class Parameters
    {
    public:
        /// [in] Number of elements in the sub-mesh array.
        uint32_t subMeshCount;
        /// [in] Array of sub-meshes to update.
        const GraphicsSceneObject::SubMeshData* pSubMeshes;
        /// [in] Array of graphics scene objects.
        const GraphicsSceneObject* pSceneObjects;
        /// [out] Array of buffers in which to store the constant buffer data for each sub-mesh.
        float32_t* const* ppConstantBufferData;

        /// @name Construction/Destruction
        //@{
        inline Parameters();
        //@}
    };

    /// @name Construction/Destruction
    //@{
    inline UpdateGraphicsSceneSubMeshBuffersJobSpawner();
    inline ~UpdateGraphicsSceneSubMeshBuffersJobSpawner();
    //@}

    /// @name Parameters
    //@{
    inline Parameters& GetParameters();
    inline const Parameters& GetParameters() const;
    inline void SetParameters( const Parameters& rParameters );
    //@}

    /// @name Job Execution
    //@{
    void Run( JobContext* pContext );
    inline static void RunCallback( void* pJob, JobContext* pContext );
    //@}

private:
    Parameters m_parameters;
};

/// Update the constant buffer data for a set of graphics scene objects.
class LUNAR_GRAPHICS_JOBS_API UpdateGraphicsSceneObjectBuffersJob : Lunar::NonCopyable
{
public:
    class Parameters
    {
    public:
        /// [in] Number of elements in the scene object array.
        uint32_t sceneObjectCount;
        /// [in] Array of scene objects to update.
        const GraphicsSceneObject* pSceneObjects;
        /// [out] Array of buffers in which to store the constant buffer data for each scene object.
        float32_t* const* ppConstantBufferData;

        /// @name Construction/Destruction
        //@{
        inline Parameters();
        //@}
    };

    /// @name Construction/Destruction
    //@{
    inline UpdateGraphicsSceneObjectBuffersJob();
    inline ~UpdateGraphicsSceneObjectBuffersJob();
    //@}

    /// @name Parameters
    //@{
    inline Parameters& GetParameters();
    inline const Parameters& GetParameters() const;
    inline void SetParameters( const Parameters& rParameters );
    //@}

    /// @name Job Execution
    //@{
    void Run( JobContext* pContext );
    inline static void RunCallback( void* pJob, JobContext* pContext );
    //@}

private:
    Parameters m_parameters;
};

/// Update the constant buffer data for a set of graphics scene object sub-meshes.
class LUNAR_GRAPHICS_JOBS_API UpdateGraphicsSceneSubMeshBuffersJob : Lunar::NonCopyable
{
public:
    class Parameters
    {
    public:
        /// [in] Number of elements in the sub-mesh array.
        uint32_t subMeshCount;
        /// [in] Array of sub-meshes to update.
        const GraphicsSceneObject::SubMeshData* pSubMeshes;
        /// [in] Array of graphics scene objects.
        const GraphicsSceneObject* pSceneObjects;
        /// [out] Array of buffers in which to store the constant buffer data for each sub-mesh.
        float32_t* const* ppConstantBufferData;

        /// @name Construction/Destruction
        //@{
        inline Parameters();
        //@}
    };

    /// @name Construction/Destruction
    //@{
    inline UpdateGraphicsSceneSubMeshBuffersJob();
    inline ~UpdateGraphicsSceneSubMeshBuffersJob();
    //@}

    /// @name Parameters
    //@{
    inline Parameters& GetParameters();
    inline const Parameters& GetParameters() const;
    inline void SetParameters( const Parameters& rParameters );
    //@}

    /// @name Job Execution
    //@{
    void Run( JobContext* pContext );
    inline static void RunCallback( void* pJob, JobContext* pContext );
    //@}

private:
    Parameters m_parameters;
};

}  // namespace Lunar

#include "GraphicsJobs/GraphicsJobsInterface.inl"

#endif  // LUNAR_GRAPHICS_JOBS_GRAPHICS_JOBS_INTERFACE_H
